
package clienteHabitacion;

import clienteHabitacion.sop_rmi.ClsAsintomaticoCllbckImpl;
import clienteHabitacion.utilidades.UtilidadesConsola;
import clienteHabitacion.utilidades.UtilidadesRegistroC;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import static java.lang.System.exit;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import servidorAlertas.dto.ClsAsintomaticoDTO;
import servidorAlertas.sop_rmi.GestionAsintomaticosInt;


public class GUICliente extends javax.swing.JFrame implements Runnable{

    private static GestionAsintomaticosInt objetoRemotoServidorAlertas;
    private HashMap<Integer, ClsAsintomaticoDTO> pacientes;
    private HashMap<Integer,Boolean> procesos;
    FondoPanel fondo = new FondoPanel();
    CardLayout cardLayout;
    /** Creates new form GUICliente */
    public GUICliente() {
        this.setContentPane(fondo);
        initComponents();   
        ImageIcon imagenDoctor = new ImageIcon(getClass().getResource("/imagenes/doctor.png"));
        Icon fondoDoctor = new ImageIcon(imagenDoctor.getImage().getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_DEFAULT));
        jLabelImagen.setIcon(fondoDoctor);
        this.repaint();
        procesos = new HashMap();
        pacientes = new HashMap();
        jButtonConsultar.setEnabled(false);
        jButtonEnviarIndicadores.setEnabled(false);
        
        cardLayout = (CardLayout) (jPanelCardLayout.getLayout());
                
    }
    
    public void limpiarPanelRegistrar(){
        buttonGroupTipo.clearSelection();
        jTextFieldId.setText("");
        jTextFieldNombres.setText("");
        jTextFieldApellidos.setText("");
        jTextFieldDireccion.setText("");
    }
    public void fijarAlerta(String mensaje){
        appendToPane(jTextPaneArea, mensaje+"\n", Color.red);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonEnviarIndicadores = new javax.swing.JButton();
        jPanelCardLayout = new javax.swing.JPanel();
        jPanelRegistrar = new FondoPanelConsulta();
        jLabelTipoId = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jButtonRegistrarPaciente = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jRadioButtonCC = new javax.swing.JRadioButton();
        jRadioButtonTI = new javax.swing.JRadioButton();
        jRadioButtonPP = new javax.swing.JRadioButton();
        jLabelApellido = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldNombres = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabelImagen = new javax.swing.JLabel();
        jPanelConsultar = new FondoPanelConsulta();
        jTextFieldIdConsulta = new javax.swing.JTextField();
        jLabelIdConsulta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsultas = new javax.swing.JTextArea();
        jButtonBuscar = new javax.swing.JButton();
        jPanelIndicadores = new FondoPanelIndicadores();
        jTextFieldIdIndicador = new javax.swing.JTextField();
        jLabelIdIndicador = new javax.swing.JLabel();
        jButtonEnviar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneArea = new javax.swing.JTextPane();
        jButtonDetener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonEnviarIndicadores.setText("Enviar Indicadores");
        jButtonEnviarIndicadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarIndicadoresActionPerformed(evt);
            }
        });

        jPanelCardLayout.setLayout(new java.awt.CardLayout());

        jPanelRegistrar.setName(""); // NOI18N
        jPanelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTipoId.setText("Tipo de identificacion");
        jPanelRegistrar.add(jLabelTipoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabelId.setText("Numero de identificacion");
        jPanelRegistrar.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 80, -1, -1));

        jLabelNombre.setText("Nombre");
        jPanelRegistrar.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 118, -1, -1));

        jButtonRegistrarPaciente.setText("Registrar");
        jButtonRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPacienteActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jButtonRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanelRegistrar.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        buttonGroupTipo.add(jRadioButtonCC);
        jRadioButtonCC.setText("CC");
        jPanelRegistrar.add(jRadioButtonCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        buttonGroupTipo.add(jRadioButtonTI);
        jRadioButtonTI.setText("TI");
        jPanelRegistrar.add(jRadioButtonTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        buttonGroupTipo.add(jRadioButtonPP);
        jRadioButtonPP.setText("PP");
        jPanelRegistrar.add(jRadioButtonPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabelApellido.setText("Apellido");
        jPanelRegistrar.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 156, -1, -1));

        jLabelDireccion.setText("Direccion de domicilio");
        jPanelRegistrar.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 194, -1, -1));

        jTextFieldNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombresKeyTyped(evt);
            }
        });
        jPanelRegistrar.add(jTextFieldNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 198, -1));

        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyTyped(evt);
            }
        });
        jPanelRegistrar.add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 198, -1));

        jTextFieldDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDireccionKeyTyped(evt);
            }
        });
        jPanelRegistrar.add(jTextFieldDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 198, -1));

        jTextFieldId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdKeyTyped(evt);
            }
        });
        jPanelRegistrar.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 198, -1));
        jPanelRegistrar.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 150, 220));

        jPanelCardLayout.add(jPanelRegistrar, "cardRegistrar");

        jTextFieldIdConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdConsultaActionPerformed(evt);
            }
        });
        jTextFieldIdConsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdConsultaKeyTyped(evt);
            }
        });

        jLabelIdConsulta.setText("Numero de identificacion");

        jTextAreaConsultas.setColumns(20);
        jTextAreaConsultas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsultas);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConsultarLayout = new javax.swing.GroupLayout(jPanelConsultar);
        jPanelConsultar.setLayout(jPanelConsultarLayout);
        jPanelConsultarLayout.setHorizontalGroup(
            jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelConsultarLayout.createSequentialGroup()
                        .addComponent(jLabelIdConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelConsultarLayout.setVerticalGroup(
            jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdConsulta)
                    .addComponent(jTextFieldIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCardLayout.add(jPanelConsultar, "cardConsultar");

        jTextFieldIdIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdIndicadorActionPerformed(evt);
            }
        });
        jTextFieldIdIndicador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIdIndicadorKeyTyped(evt);
            }
        });

        jLabelIdIndicador.setText("Numero de identificacion");

        jButtonEnviar.setText("Iniciar Indicadores");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTextPaneArea);

        jButtonDetener.setText("Detener indicadores");
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIndicadoresLayout = new javax.swing.GroupLayout(jPanelIndicadores);
        jPanelIndicadores.setLayout(jPanelIndicadoresLayout);
        jPanelIndicadoresLayout.setHorizontalGroup(
            jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIdIndicador)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIdIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEnviar))
                    .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDetener)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelIndicadoresLayout.setVerticalGroup(
            jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIndicadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIndicadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdIndicador)
                    .addComponent(jButtonEnviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDetener)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanelCardLayout.add(jPanelIndicadores, "cardIndicadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnviarIndicadores, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(620, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addComponent(jPanelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEnviarIndicadores, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        //jPanelRegistrar.setSize(400,300);
        //jPanelRegistrar.setLocation(5,5);
        //jPanelMenu.setVisible(false);
        cardLayout.show(jPanelCardLayout, "cardRegistrar");
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
       cardLayout.show(jPanelCardLayout, "cardConsultar");
       
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonEnviarIndicadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarIndicadoresActionPerformed
        // TODO add your handling code here:
        cardLayout.show(jPanelCardLayout, "cardIndicadores");
        
       
    }//GEN-LAST:event_jButtonEnviarIndicadoresActionPerformed

    private void jButtonRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPacienteActionPerformed
        // TODO add your handling code here:
        String tipo_id="";
        
       if((!jRadioButtonCC.isSelected() && !jRadioButtonTI.isSelected() && !jRadioButtonPP.isSelected()) ||
          jTextFieldId.getText().isEmpty() || jTextFieldNombres.getText().isEmpty() || 
          jTextFieldApellidos.getText().isEmpty() || jTextFieldDireccion.getText().isEmpty()) 
        {
               JOptionPane.showMessageDialog(null, "Datos requeridos no deben estar vacios!!!");
        }else
        {
            if(jRadioButtonCC.isSelected())
                tipo_id = "CC";
            if(jRadioButtonTI.isSelected())
                tipo_id = "TI";
            if(jRadioButtonPP.isSelected())
                tipo_id = "PP";
        
            ClsAsintomaticoDTO paciente = new ClsAsintomaticoDTO(jTextFieldNombres.getText(),jTextFieldApellidos.getText(),tipo_id, Integer.parseInt(jTextFieldId.getText()), jTextFieldDireccion.getText());
            ClsAsintomaticoCllbckImpl asintomatico;

            try {
                asintomatico = new ClsAsintomaticoCllbckImpl(paciente,this);
                if(objetoRemotoServidorAlertas.registrarAsintomatico(asintomatico) ){
                    JOptionPane.showMessageDialog(null, "Se registro paciente exitosamente!!!");
                    pacientes.put(Integer.parseInt(jTextFieldId.getText()), paciente);
                    limpiarPanelRegistrar();
                    jButtonConsultar.setEnabled(true);
                    jButtonEnviarIndicadores.setEnabled(true);
                }else
                    JOptionPane.showMessageDialog(null, "No se registro el paciente!!!");

            } catch (RemoteException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }    
        }
    }//GEN-LAST:event_jButtonRegistrarPacienteActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        if(jTextFieldIdConsulta.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Dato requerido no debe estar vacio!!!");
        }else
        {    
            try {
                // TODO add your handling code here:
                ClsAsintomaticoDTO pacienteAsintomatico = objetoRemotoServidorAlertas.consultarAsintomatico(Integer.parseInt(jTextFieldIdConsulta.getText()) );
                if(pacienteAsintomatico != null)
                {
                    jTextAreaConsultas.append("Datos del paciente asintomatico\n");
                    jTextAreaConsultas.append("Nombres: "+pacienteAsintomatico.getNombres()+"\n");
                    jTextAreaConsultas.append("Apellidos: "+pacienteAsintomatico.getApellidos()+"\n");
                    jTextAreaConsultas.append("Tipo de Id: "+pacienteAsintomatico.getTipo_id()+"\n");
                    jTextAreaConsultas.append("Id: "+pacienteAsintomatico.getId()+"\n");
                    jTextAreaConsultas.append("Direccion: "+pacienteAsintomatico.getDireccion()+"\n");
                    jTextAreaConsultas.append("Datos del paciente asintomatico consultados exitosamente!!!\n");
                }else
                {
                    JOptionPane.showMessageDialog(null, "El paciente con id "+jTextFieldIdConsulta.getText()+" no existe!!!"); 
                }
                
            } catch (RemoteException ex) {
                Logger.getLogger(GUICliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
        Thread enviarIndicadores = new Thread(this);
        enviarIndicadores.start();
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdKeyTyped
        // TODO add your handling code here:
        int longitudCadena = 0;
        char c = evt.getKeyChar();
        if((c < '0' || c > '9') && (c!= KeyEvent.VK_BACK_SPACE))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Ingrese solo numeros!!!");
        }
        
        longitudCadena = jTextFieldId.getText().length();
        if(longitudCadena >= 5)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"El id del paciente debe estar entre 0 y 99999!!!");
        }
    
    }//GEN-LAST:event_jTextFieldIdKeyTyped

    private void jTextFieldNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombresKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_BACK_SPACE) && (c != ' ') && (c !='ñ')&& (c !='Ñ'))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Ingrese solo letras!!!");
        }
        
        if(jTextFieldNombres.getText().length() >= 30)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"El nombre del paciente debe ser maximo de 30 caracteres!!!");
        }
        
    }//GEN-LAST:event_jTextFieldNombresKeyTyped

    private void jTextFieldApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != KeyEvent.VK_BACK_SPACE) && (c != ' ') && (c !='ñ')&& (c !='Ñ'))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Ingrese solo letras!!!");
        }
        
        if(jTextFieldApellidos.getText().length() >= 30)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"El apellido del paciente debe ser maximo de 30 caracteres!!!");
        }
    }//GEN-LAST:event_jTextFieldApellidosKeyTyped

    private void jTextFieldDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDireccionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < '0' || c > '9') && (c != KeyEvent.VK_BACK_SPACE) && (c != ' ') && (c !='ñ')&& (c !='Ñ') && (c !='#') && (c !='-') && (c !='.') && (c !='/' ))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Caracter incorrecto para la direccion!!!");
        }
        
        if(jTextFieldDireccion.getText().length() >= 30)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"La direccion del paciente debe ser maximo de 30 caracteres!!!");
        }
    }//GEN-LAST:event_jTextFieldDireccionKeyTyped

    private void jTextFieldIdConsultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdConsultaKeyTyped
        // TODO add your handling code here:
        int longitudCadena = 0;
        char c = evt.getKeyChar();
        if((c < '0' || c > '9') && (c!= KeyEvent.VK_BACK_SPACE))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Ingrese solo numeros!!!");
        }
        
        longitudCadena = jTextFieldIdConsulta.getText().length();
        if(longitudCadena >= 5)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"El id del paciente debe estar entre 0 y 99999!!!");
        }
    }//GEN-LAST:event_jTextFieldIdConsultaKeyTyped

    private void jTextFieldIdIndicadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIdIndicadorKeyTyped
        // TODO add your handling code here:
        int longitudCadena = 0;
        char c = evt.getKeyChar();
        if((c < '0' || c > '9') && (c!= KeyEvent.VK_BACK_SPACE))
        {   evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Ingrese solo numeros!!!");
        }
        
        longitudCadena = jTextFieldIdIndicador.getText().length();
        if(longitudCadena >= 5)
        {
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"El id del paciente debe estar entre 0 y 99999!!!");
        }
    }//GEN-LAST:event_jTextFieldIdIndicadorKeyTyped

    private void jTextFieldIdConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdConsultaActionPerformed

    private void jTextFieldIdIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdIndicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdIndicadorActionPerformed

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        // TODO add your handling code here:
        if(jTextFieldIdIndicador.getText() != ""){
            int id = Integer.parseInt(jTextFieldIdIndicador.getText() );
            if(procesos.containsKey(id) && procesos.get(id)){
                procesos.put(id, false);
            }else{
                JOptionPane.showMessageDialog(null, "Enviar indicadores del paciente con id "+id+" no se esta ejecutando");
            }
        }else
            JOptionPane.showMessageDialog(null, "Ingrese numero de identificacion");
        
    }//GEN-LAST:event_jButtonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NotBoundException, MalformedURLException, RemoteException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        int numPuertoRMIRegistry = 0;
        String direccionIpRMIRegistry = "";
        if(args.length == 0){           
            System.out.print("Cual es la direccion ip donde se encuentra el rmiregistry: ");
            direccionIpRMIRegistry = UtilidadesConsola.leerCadena();
            System.out.print("Cual es el numero de puerto por el cual escucha el rmiregistry: ");	
            numPuertoRMIRegistry = UtilidadesConsola.leerEntero();
        }else{
            direccionIpRMIRegistry = args[0];
            numPuertoRMIRegistry = Integer.parseInt(args[1]);
        }
        objetoRemotoServidorAlertas = (GestionAsintomaticosInt)UtilidadesRegistroC.ObtenerObjRemoto(direccionIpRMIRegistry, numPuertoRMIRegistry,"ObjetoGestionAsintomaticos");
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICliente().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonEnviarIndicadores;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRegistrarPaciente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdConsulta;
    private javax.swing.JLabel jLabelIdIndicador;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoId;
    private javax.swing.JPanel jPanelCardLayout;
    private javax.swing.JPanel jPanelConsultar;
    private javax.swing.JPanel jPanelIndicadores;
    private javax.swing.JPanel jPanelRegistrar;
    private javax.swing.JRadioButton jRadioButtonCC;
    private javax.swing.JRadioButton jRadioButtonPP;
    private javax.swing.JRadioButton jRadioButtonTI;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaConsultas;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdConsulta;
    private javax.swing.JTextField jTextFieldIdIndicador;
    private javax.swing.JTextField jTextFieldNombres;
    private javax.swing.JTextPane jTextPaneArea;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        if(jTextFieldIdIndicador.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Dato requerido no debe estar vacio!!!");
        }
        else
        {    try 
             {
                int id = Integer.parseInt(jTextFieldIdIndicador.getText() );
                if(!procesos.containsKey(id))
                    procesos.put(id, false);
                if(procesos.get(id)){
                    JOptionPane.showMessageDialog(null, "ya existe un proceso enviar indicadores para el paciente con id "+id);
                }else{
                    ClsAsintomaticoDTO pacienteAsintomatico = objetoRemotoServidorAlertas.consultarAsintomatico(id);
                    if(pacienteAsintomatico != null)    
                    {
                        if(pacientes.containsKey(id)){
                            procesos.put(id, true);
                            while (procesos.get(id)) {
                                //hacemos un ciclo infinito
                                try {
                                    float ToC = (float) (Math.random() * 7 + 35);
                                    int fCardiaca = (int) (Math.random() * 31 + 55);
                                    int fRespiratoria = (int) (Math.random() * 31 + 65);
                                    appendToPane(jTextPaneArea, "\nEnviando indicadores...\n", Color.blue);
                                    appendToPane(jTextPaneArea, "Paciente: "+pacienteAsintomatico.getNombres()+" "+pacienteAsintomatico.getApellidos()+"\n", Color.blue);
                                    appendToPane(jTextPaneArea, pacienteAsintomatico.getTipo_id()+": "+pacienteAsintomatico.getId()+"\n", Color.blue);
                                    appendToPane(jTextPaneArea, "Frecuencia cardiaca: " + fCardiaca+"\n", Color.black);
                                    appendToPane(jTextPaneArea, "Frecuencia respiratoria: " + fRespiratoria+"\n", Color.black);
                                    appendToPane(jTextPaneArea, "Temperatura: " + ToC + " C.\n", Color.black);
                                    objetoRemotoServidorAlertas.enviarIndicadores(id, fCardiaca, fRespiratoria, ToC);


                                    Thread.sleep(8000);

                                } catch (InterruptedException e) {
                                    e.printStackTrace();
                                }
                            }
                            appendToPane(jTextPaneArea, "Ha finalizado el proceso enviar indicadores para el paciente "+pacienteAsintomatico.getTipo_id()+": "+pacienteAsintomatico.getId()+" "+pacienteAsintomatico.getNombres()+" "+pacienteAsintomatico.getApellidos()+"\n", Color.GREEN);
                        }else{
                            JOptionPane.showMessageDialog(null, "El paciente con id "+id+" no ha sido registrado en este cliente!!!");
                        }
                    }else
                    {
                        JOptionPane.showMessageDialog(null, "El paciente con id "+id+" no existe!!!"); 
                    }
                }

            } catch (RemoteException e) {
                System.out.println("La operacion no se pudo completar, intente nuevamente...");
                System.out.println("Excepcion generada: " + e.getMessage());
            }
        }
    }
    //metodo para adicionar texto con color a un jTextPaneArea
    private void appendToPane(JTextPane tp, String msg, Color c)
    {
        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, c);

        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);

        int len = tp.getDocument().getLength();
        tp.setCaretPosition(len);
        tp.setCharacterAttributes(aset, false);
        tp.replaceSelection(msg);
        

    }

    class FondoPanel extends JPanel{
        private Image imagenFondo;
        @Override
        public void paint(Graphics g){
            imagenFondo = new ImageIcon(getClass().getResource("/imagenes/coronavirus-hospital-sant-joan-deu-barcelona.jpg")).getImage();
            g.drawImage(imagenFondo, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    class FondoPanelConsulta extends JPanel{
        private Image imagenFondo;
        @Override
        public void paint(Graphics g){
            imagenFondo = new ImageIcon(getClass().getResource("/imagenes/frecuencia.jpg")).getImage();
            g.drawImage(imagenFondo, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
        
    class FondoPanelIndicadores extends JPanel{
        private Image imagenFondo;
        @Override
        public void paint(Graphics g){
            imagenFondo = new ImageIcon(getClass().getResource("/imagenes/frecuencia.jpg")).getImage();
            g.drawImage(imagenFondo, 0, 0, getWidth(),getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
}
